name: detect

on: 
  schedule:
   - cron: '12 21 * * 3'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Detect IPs
      run: | 
        echo "$(TZ='Asia/Shanghai' date +%Y-%m-%d\ %T) start" > time.log
        python DetectIPHTTPS.py
        echo "$(TZ='Asia/Shanghai' date +%Y-%m-%d\ %T) end" >> time.log 
    - name: Commit
      run: |
        git config --local user.email 50695187+tr1s7an@users.noreply.github.com
        git config --local user.name tr1s7an
        git add .
        git commit -m "Update results" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
